baseURL = 'https://wsgggws.github.io/'
languageCode = 'zh-cn'
title = 'Blogs (码码要洗手)'
theme = 'hugo-theme-stack'
# Default Content Language
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

[menu]
    [[menu.main]]
        identifier = "home"
        name = "首页"
        url = "/"
        weight = 1
        [menu.main.params]
            icon = "home"

    [[menu.main]]
        identifier = "about"
        name = "关于我"
        url = "/about/"
        weight = 2
        [menu.main.params]
            icon = "user"

[params]
    mainSections = ["blogs"]
    featuredImageField = "image"
    favicon = "/images/website/Navy.ico"
    rssFullContent = true

    [params.sidebar]
        emoji = "🍥"
        subtitle = "" 
        [params.sidebar.avatar]
            enabled = true
            local = false
            src = "/images/website/Navy.ico"

    [params.article]
        math = true
        toc = true
        readingTime = true
        [params.article.license]
            enabled = false
        
    [params.footer]
        since = 2020

    [params.widgets]
        [[params.widgets.homepage]]
            type = "search"

        [[params.widgets.homepage]]
            type = "archives"
            [params.widgets.homepage.params]
                limit = 5

        [[params.widgets.homepage]]
            type = "categories"
            [params.widgets.homepage.params]
                limit = 10

        [[params.widgets.homepage]]
            type = "tag-cloud"
            [params.widgets.homepage.params]
                limit = 10

        [[params.widgets.page]]
            type = "toc"
