baseURL = 'https://wsgggws.github.io/'
languageCode = 'en-us'
title = 'Blogs (码码冇得空)'
theme = 'paper'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "AboutMe"
    url = "/about/"
    weight = 10


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # github = ''                 # github.com/YOUR_GITHUB_ID
  rss = true                                    # show rss icon

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = ''         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = ""  # use graph comment (disqus alternative)
  favicon = "/images/website/Navy.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon
